#!/bin/bash

#runs though the security groups to see if the ip address is there

ipaddress=$1
region=$2

for i in "$@"
do
echo $i
ip=$(aws ec2 describe-security-groups --region $region --query "SecurityGroups[?IpPermissions[?IpRanges[?CidrIp=='$i']]].GroupName")
echo $ip
done
