#!/bin/bash

move() {
	mv "$FILE" /home/ec2-user/sharland/"$FILE"
}
move2() {
	mv "$FILE" /home/ec2-user/sharland/home/"$FILE"
}
inserted() {
	read -e -p "1 or 2: "
	case "$REPLY" in
		1)
			move
			ls /home/ec2-user/sharland >> test1.csv
			;;
		2)
			move2
			ls /home/ec2-user/sharland/home >> test2.csv
			;;
	esac
}

cd /home/ec2-user/kevin/ && ls | sort

read -e -p 'Please enter file name: ' FILE
	if [ -d "$FILE" ]
		then
			echo "Directory Exists"
			inserted
        elif [ -f "$FILE" ]
        	then
        		echo "File Exists"
			inserted
	else
		echo "Does Not Exist"
	fi
