#!/bin/bash

echo "
US West (Oregon)                Region  us-west-2
US West (N. California)         Region  us-west-1
US East (Ohio)                  Region  us-east-2
US East (N. Virginia)           Region  us-east-1
Asia Pacific (Mumbai)           Region  ap-south-1
Asia Pacific (Seoul)            Region  ap-northeast-2
Asia Pacific (Singapore)        Region  ap-southeast-1
Asia Pacific (Sydney)           Region  ap-southeast-2
Asia Pacific (Tokyo)            Region  ap-northeast-1
Canada (Central)                Region  ca-central-1
China (Beijing)                 Region  cn-north-1
EU (Frankfurt)                  Region  eu-central-1
EU (Ireland)                    Region  eu-west-1
EU (London)                     Region  eu-west-2
EU (Paris)                      Region  eu-west-3
South America (São Paulo)       Region  sa-east-1
AWS GovCloud (US)               us-gov-west-1

"

