#!/bin/bash

echo "
US West (Oregon)         	us-west-2
US West (N. California)  	us-west-1
US East (Ohio)           	us-east-2
US East (N. Virginia)    	us-east-1
Asia Pacific (Mumbai)    	ap-south-1
Asia Pacific (Seoul)     	ap-northeast-2
Asia Pacific (Singapore) 	ap-southeast-1
Asia Pacific (Sydney)    	ap-southeast-2
Asia Pacific (Tokyo)     	ap-northeast-1
Canada (Central)         	ca-central-1
China (Beijing)          	cn-north-1
EU (Frankfurt)           	eu-central-1
EU (Ireland)             	eu-west-1
EU (London)              	eu-west-2
EU (Paris)               	eu-west-3
South America (São Paulo)	sa-east-1
AWS GovCloud (US)        	us-gov-west-1
"

